# Generated by Django 3.2.16 on 2023-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contact_customer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='question_categories',
            field=models.CharField(choices=[('licence', 'Licence Type'), ('maintenance', 'Maintenance'), ('sales', 'Sales'), ('shipping_charges', 'Shipping Charges'), ('refunds_returns', 'Refunds and Returns'), ('warranty', 'Warranty Queries'), ('other', 'Other Queries')], default='certification', max_length=50, verbose_name='What does your query relate to?'),
        ),
    ]
