# Generated by Django 3.2.16 on 2023-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='licence',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a', 'A')], default='All', max_length=50),
        ),
    ]
