# Generated by Django 3.2.16 on 2023-01-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_licence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['manufacturer']},
        ),
    ]
