# Generated by Django 3.2.16 on 2023-01-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_username_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
