# Generated by Django 3.2.16 on 2023-01-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orderitem_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('date_ordered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_purchased', to='store.orderitem')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchased', to='store.orderitem')),
                ('quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_purchased', to='store.orderitem')),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='store.orderitem')),
            ],
        ),
    ]
