# Generated by Django 3.2.16 on 2023-01-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
