# Generated by Django 3.2.16 on 2023-01-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_comment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
