# Generated by Django 3.2.16 on 2023-01-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
